### ISSUE TITLE
Array brackets not rendered properly in LaTeX

### ISSUE THREAD

**Issue by johnblommers** [bgallois/OpenJournal#2]
OpenJournal v1.1.0 on Linux does not properly render this array:

```tex
\\[
\begin{bmatrix}
1 & 2 & 3\\\
a & b & c
\end{bmatrix}
\\]
```

The brackets are not tall enough:

![Screenshot from 2021-11-23 12-54-14](https://user-images.githubusercontent.com/8484427/143118204-4b03b536-d365-4147-ab10-61d6835eea11.png)

**Comment by bgallois** [comment]
LaTeX rendering issues has been fixed with 321621d34c82367f6bfac7b75ec92f7e85d54953.  
You can try a nightly build of OpenJournal by downloading the artifact from the GitHub Actions build job https://github.com/bgallois/OpenJournal/actions/runs/1495650141. The fix will be release in the next version.
